package com.cabbagebeyond.util

enum class Feature(val value: String) {
    CONFIGURE_APP("CONFIGURE_APP"),
    LIST_WORLD("LIST_WORLD"),
    LIST_WORLD_SAVAGE_WORLDS("LIST_WORLD_SAVAGEWORLDS"),
    LIST_WORLD_SHADOW_RUN("LIST_WORLD_SHADOWRUN"),
    LIST_WORLD_DND5E("LIST_WORLD_DND5E"),
    DETAIL_WORLD_SAVAGE_WORLDS("DETAIL_WORLD_SAVAGEWORLDS"),
    DETAIL_WORLD_SHADOW_RUN("DETAIL_WORLD_SHADOWRUN"),
    DETAIL_WORLD_DND5E("DETAIL_WORLD_DND5E"),
    LIST_STORY_SAVAGE_WORLDS("LIST_STORY_SAVAGEWORLDS"),
    LIST_STORY_SHADOW_RUN("LIST_STORY_SHADOWRUN"),
    LIST_STORY_DND5E("LIST_STORY_DND5E"),
    DETAIL_STORY_SAVAGE_WORLDS("DETAIL_STORY_SAVAGEWORLDS"),
    DETAIL_STORY_SHADOW_RUN("DETAIL_STORY_SHADOWRUN"),
    DETAIL_STORY_DND5E("DETAIL_STORY_DND5E"),
    LIST_SAVAGE_WORLDS("LIST_SAVAGEWORLDS"),
    DETAIL_SAVAGE_WORLDS("DETAIL_SAVAGEWORLDS"),
    READ_SAVAGE_WORLDS("READ_SAVAGEWORLDS"),
    DETAIL_SESSION_SAVAGE_WORLDS("DETAIL_SESSION_SAVAGEWORLDS")
}
