package com.cabbagebeyond.util

enum class Feature(value: String) {
    CONFIGURE_APP("CONFIGURE_APP"),
    LIST_WORLD("LIST_WORLD"),
    LIST_WORLD_SAVAGEWORLDS("LIST_WORLD_SAVAGEWORLDS"),
    LIST_WORLD_SHADOWRUN("LIST_WORLD_SHADOWRUN"),
    LIST_WORLD_DND5E("LIST_WORLD_DND5E"),
    DETAIL_WORLD_SAVAGEWORLDS("DETAIL_WORLD_SAVAGEWORLDS"),
    DETAIL_WORLD_SHADOWRUN("DETAIL_WORLD_SHADOWRUN"),
    DETAIL_WORLD_DND5E("DETAIL_WORLD_DND5E"),
    LIST_STORY_SAVAGEWORLDS("LIST_STORY_SAVAGEWORLDS"),
    LIST_STORY_SHADOWRUN("LIST_STORY_SHADOWRUN"),
    LIST_STORY_DND5E("LIST_STORY_DND5E"),
    DETAIL_STORY_SAVAGEWORLDS("DETAIL_STORY_SAVAGEWORLDS"),
    DETAIL_STORY_SHADOWRUN("DETAIL_STORY_SHADOWRUN"),
    DETAIL_STORY_DND5E("DETAIL_STORY_DND5E"),
    LIST_SAVAGEWORLDS("LIST_SAVAGEWORLDS"),
    DETAIL_SAVAGEWORLDS("DETAIL_SAVAGEWORLDS"),
    READ_SAVAGEWORLDS("READ_SAVAGEWORLDS"),
    DETAIL_SESSION_SAVAGEWORLDS("DETAIL_SESSION_SAVAGEWORLDS")
}
